#!/usr/bin/env python3
#
# SPDX-License-Identifier: MIT
# Copyright (c) 2024- Karel Brinda
"""
galitime - benchmarking of shell commands with normalized timing and resource output.

Author: Karel Brinda <karel.brinda@inria.fr>
Homepage: https://github.com/karel-brinda/galitime
Issues: https://github.com/karel-brinda/galitime/issues
License: MIT

MIT License

Copyright (c) 2024- Karel Brinda

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import argparse
import collections
import datetime
import os
import shlex
import re
import shutil
import statistics
import subprocess
import sys
import tempfile

from abc import ABC, abstractmethod

from pathlib import Path

PROGRAM = 'galitime'
DESC = 'benchmarking of computational experiments using GNU time'
__version__ = "0.4.0"
__author__ = "Karel Brinda"
__email__ = "karel.brinda@inria.fr"
__license__ = "MIT"
__url__ = "https://github.com/karel-brinda/galitime"
__issues_url__ = "https://github.com/karel-brinda/galitime/issues"

DEFAULT_l = "stderr"
DEFAULT_r = 1
DEFAULT_s = '/usr/bin/env bash'
DEFAULT_s = shutil.which('bash')
NA_VALUE = "NA"
STATUS_OK = "ok"
STATUS_FAILED = "failed"
STATUS_TIMEOUT = "timeout"
STATUS_TIMING_ERROR = "timing_error"
STATS_COLUMNS = (
    "experiment", "runs_requested", "runs_completed", "runs_summarized", "runs_ok",
    "runs_failed", "runs_timeout", "runs_timing_error", "final_status", "final_exit_code",
    "real_s_mean", "real_s_stddev", "real_s_min", "real_s_median", "real_s_max",
    "user_s_mean", "user_s_stddev", "user_s_min", "user_s_median", "user_s_max",
    "sys_s_mean", "sys_s_stddev", "sys_s_min", "sys_s_median", "sys_s_max",
    "cpu_s_mean", "cpu_s_stddev", "cpu_s_min", "cpu_s_median", "cpu_s_max",
    "cpu_pct_mean", "cpu_pct_stddev", "cpu_pct_min", "cpu_pct_median", "cpu_pct_max",
    "max_ram_kb_mean", "max_ram_kb_stddev", "max_ram_kb_min", "max_ram_kb_median",
    "max_ram_kb_max", "command"
)
STATS_NUMERIC_METRICS = (
    "real_s", "user_s", "sys_s", "cpu_s", "cpu_pct", "max_ram_kb"
)


def log_debug(enabled, message):
    if enabled:
        timestamp = datetime.datetime.now().isoformat(timespec="seconds")
        prefix = f"[{PROGRAM} {timestamp}]"
        if sys.stderr.isatty():
            prefix = f"\033[1m{prefix}\033[0m"
        print(f"{prefix} {message}", file=sys.stderr, flush=True)


def split_cli_argv(parser, argv):
    flag_options = set()
    value_options = set()
    long_value_options = set()
    for action in parser._actions:
        if not action.option_strings:
            continue
        if action.nargs == 0:
            flag_options.update(action.option_strings)
        else:
            value_options.update(action.option_strings)
            long_value_options.update(x for x in action.option_strings if x.startswith("--"))

    option_argv = []
    i = 0
    while i < len(argv):
        arg = argv[i]
        if arg == "--":
            return option_argv, argv[i + 1:], False
        if arg in flag_options:
            option_argv.append(arg)
            i += 1
            continue
        if arg in value_options:
            option_argv.append(arg)
            if i + 1 < len(argv):
                option_argv.append(argv[i + 1])
                i += 2
            else:
                i += 1
            continue
        if any(arg.startswith(f"{opt}=") for opt in long_value_options):
            option_argv.append(arg)
            i += 1
            continue
        if arg.startswith("-") and arg != "-":
            # Hand ambiguous or unknown leading option-like tokens back to argparse
            # so it can emit its normal diagnostics and handle its own accepted forms.
            return None, None, True
        return option_argv, argv[i:], False
    return option_argv, [], False


# IMPORTANT NOTE: some results are parsed from text files so no assumptions should be made
# the integers being converted to int from str
class TimingResult:
    PRINTED_COLUMNS = (
        "experiment", "run", "real_s", "user_s", "sys_s", "cpu_s", "cpu_pct", "max_ram_kb",
        "status", "exit_code", "command"
    )

    def __init__(self, experiment=None, run=None, command=None):
        """Setup all the fields
        """
        self._data = collections.OrderedDict()

        # 1. prefill table with the mandatory fields in the right order
        mandatory_columns = (
            "experiment", "run", "real_s", "user_s", "sys_s", "cpu_s", "cpu_pct", "max_ram_kb",
            "fs_inputs", "fs_outputs", "status", "exit_code", "command"
        )
        for x in mandatory_columns:
            self.add(x, NA_VALUE)

        # 2. insert experiment parameters
        self.set('experiment', experiment)
        self.set('run', run)
        self.set('command', command)

    def __getitem__(self, key):
        return self._data[key]

    #def __setitem__(self, key, value):
    #    assert key in self._data, f"The key '{key}' is not in the TimingResult dict after initialization, likely a bug (present keys: {self._data.keys()})"
    #    self._data[key] = value

    def set(self, key, value):
        assert key in self._data, f"The key '{key}' is not in the TimingResult dict after initialization, likely a bug (present keys: {self._data.keys()})"
        self._data[key] = NA_VALUE if value is None else value

    def add(self, key, value):
        assert key not in self._data, f"The key '{key}' is already in the TimingResult dict after initialization, likely a bug (present keys: {self._data.keys()})"
        self._data[key] = NA_VALUE if value is None else value

    def __delitem__(self, key):
        del self._data[key]

    def __contains__(self, key):
        return key in self._data

    def __repr__(self):
        return repr(self._data)

    @staticmethod
    def _format_printed_value(key, value):
        if key == "cpu_pct" and value != NA_VALUE:
            return f"{value}%"
        return value

    def __str__(self):
        printed_values = [
            self._format_printed_value(k, self._data[k]) for k in self.PRINTED_COLUMNS
        ]
        return "\t".join(self.PRINTED_COLUMNS) + "\n" + "\t".join(map(str, printed_values))


class AbstractTime(ABC):

    def __init__(self, command, shell, experiment, time, debug=False):
        self.time_command = time
        self.shell = shell
        self.experiment = experiment
        self.debug = debug
        self.command = command
        self.tmp_dir = tempfile.TemporaryDirectory()
        self._dlog(f"temporary directory: {self.tmp_dir.name!r}")
        self._dlog(f"time command: {self.time_command!r}")
        self.results = []  # all processed results
        self.current_i = 0
        self.current_result = None  # currrent result
        self.final_exit_code = 0

    def __del__(self):
        tmp_dir = getattr(self, "tmp_dir", None)
        if tmp_dir is not None:
            tmp_dir.cleanup()

    def _dlog(self, message):
        log_debug(self.debug, message)

    @staticmethod
    def _normalize_exit_code(exit_code):
        if exit_code < 0:
            # SIGKILL shows up as -9 from wait(); shells conventionally report it as 137.
            return 128 + (-exit_code)
        return exit_code

    # TODO: add possibility to set up multiple repetitions
    def run(self, times=1):
        """The main loop
        """
        for i in range(times):
            self.current_i += 1
            run = self.current_i
            self._dlog(f"run {run}/{times}: starting")
            self.current_result = TimingResult(
                experiment=self.experiment, run=run, command=self.command
            )

            try:
                self._dlog(f"run {run}/{times}: executing wrapped command")
                self._execute_time()
                self._dlog(f"run {run}/{times}: parsing result")
                self._parse_result()
                self._dlog(f"run {run}/{times}: computing CPU time")
                self._set_cpu_time()
                self._dlog(f"run {run}/{times}: computing CPU percentage")
                self._set_cpu_pct()
                self._dlog(f"run {run}/{times}: setting status")
                self._set_status()
            except Exception as err:
                self._dlog(f"timing exception: {type(err).__name__}: {err!r}")
                self.current_result.set("status", STATUS_TIMING_ERROR)
                print(f"Galitime error: timing error ({err})", file=sys.stderr)
                self.final_exit_code = 1
                self._dlog(f"run {run}/{times}: saving result")
                self._save_result()
                self._dlog(
                    f"run {run}/{times}: final status={self.current_result['status']}, "
                    f"exit_code={self.current_result['exit_code']}"
                )
                break

            self._dlog(f"run {run}/{times}: saving result")
            self._save_result()

            status = self.current_result["status"]
            self._dlog(
                f"run {run}/{times}: final status={status}, "
                f"exit_code={self.current_result['exit_code']}"
            )
            if status == STATUS_OK:
                continue

            if status == STATUS_FAILED:
                exit_code = int(self.current_result['exit_code'])
                print(f"Galitime error: non-zero exit code ({exit_code})", file=sys.stderr)
                self.final_exit_code = exit_code
            elif status == STATUS_TIMEOUT:
                print("Galitime error: command timed out", file=sys.stderr)
                self.final_exit_code = 124
            else:
                self.final_exit_code = 1
            break
            #
            # TODO: Add error treatment based on the user pre-specified failure mode
            # See https://github.com/karel-brinda/galitime/issues/25
            #

    def get_final_exit_code(self):
        return self.final_exit_code

    def current_tmp_fn(self):
        return os.path.join(self.tmp_dir.name, f"timing_output.run_{self.current_i}.log")

    def current_exit_code_fn(self):
        return os.path.join(self.tmp_dir.name, f"exit_code.run_{self.current_i}.log")

    def _execute_time(self):
        """Execute time, whatever command it is
        """

        timing_output_fn = self.current_tmp_fn()
        exit_code_fn = self.current_exit_code_fn()
        self._dlog(f"timing output filename: {timing_output_fn!r}")
        self._dlog(f"exit-code filename: {exit_code_fn!r}")
        command_script = (
            f'galitime_exit_code_file={shlex.quote(exit_code_fn)}; '
            'trap \'printf "%s\\n" "$?" > "$galitime_exit_code_file"\' EXIT; '
            f'{self.command}'
        )
        self._dlog(f"command_script: {command_script!r}")
        wrapped_command = f'{self.wrapper()} {shlex.quote(self.shell)} -c {shlex.quote(command_script)}'
        self._dlog(f"wrapped command: {wrapped_command!r}")

        main_process = subprocess.Popen(wrapped_command, shell=True, executable=self.shell)
        self._dlog(f"subprocess pid: {main_process.pid}")

        #TODO: integrate timeout into the whole method
        timeout = None
        timed_out = False
        try:
            # comment: returncode not the same as int (see https://docs.python.org/3/library/subprocess.html#subprocess.Popen.returncode)
            exit_code = self._normalize_exit_code(int(main_process.wait(timeout=timeout)))
            self._dlog(f"wait return code: {exit_code}")
        except subprocess.TimeoutExpired:
            timed_out = True
            exit_code = None
            self._dlog(f"timeout while waiting for process after {timeout!r}")
        try:
            with open(exit_code_fn) as exit_code_fo:
                exit_code_lines = [x.strip() for x in exit_code_fo if x.strip()]
        except FileNotFoundError:
            exit_code_lines = []
        self._dlog(f"exit-code file lines: {exit_code_lines!r}")
        if exit_code_lines:
            if len(exit_code_lines) != 1:
                raise RuntimeError(f"Unexpected exit code output shape: {exit_code_lines!r}")
            exit_code = int(exit_code_lines[0])
        if timed_out and exit_code is None:
            self.current_result.set("status", STATUS_TIMEOUT)
        self.current_result.set("exit_code", exit_code)
        self._dlog(f"final recorded exit code: {exit_code}")

        ## TODO: different treating based on the expected behaviour

    @abstractmethod
    def _parse_result(self):
        pass

    def _set_cpu_time(self):
        user_s = float(self.current_result["user_s"])
        sys_s = float(self.current_result["sys_s"])
        self.current_result.set("cpu_s", user_s + sys_s)

    def _set_cpu_pct(self):
        real_s = float(self.current_result["real_s"])
        cpu_s = float(self.current_result["cpu_s"])
        if real_s <= 0:
            self.current_result.set("cpu_pct", None)
        else:
            self.current_result.set("cpu_pct", 100.0 * cpu_s / real_s)

    def _set_status(self):
        if self.current_result["status"] != NA_VALUE:
            return
        exit_code = int(self.current_result["exit_code"])
        if exit_code == 0:
            self.current_result.set("status", STATUS_OK)
        else:
            self.current_result.set("status", STATUS_FAILED)

    def _save_result(self):
        self.results.append(self.current_result)

    def __str__(self):
        lines = "\n".join([str(x) for x in self.results]).split("\n")
        seen = set()
        unique_list = []
        for x in lines:
            if x not in seen:
                seen.add(x)
                unique_list.append(x)
        return "\n".join(unique_list)


def _get_stats_value(results, key):
    if not results:
        return NA_VALUE
    value = results[0][key]
    return NA_VALUE if value == NA_VALUE else value


def build_stats_row(timing, runs_requested):
    results = timing.results
    summarized_results = [result for result in results if result["status"] == STATUS_OK]
    status_counts = collections.Counter(result["status"] for result in results)

    row = collections.OrderedDict()
    row["experiment"] = _get_stats_value(results, "experiment")
    row["runs_requested"] = runs_requested
    row["runs_completed"] = len(results)
    row["runs_summarized"] = len(summarized_results)
    row["runs_ok"] = status_counts.get(STATUS_OK, 0)
    row["runs_failed"] = status_counts.get(STATUS_FAILED, 0)
    row["runs_timeout"] = status_counts.get(STATUS_TIMEOUT, 0)
    row["runs_timing_error"] = status_counts.get(STATUS_TIMING_ERROR, 0)
    row["final_status"] = results[-1]["status"] if results else NA_VALUE
    row["final_exit_code"] = timing.get_final_exit_code()

    for metric in STATS_NUMERIC_METRICS:
        values = [float(result[metric]) for result in summarized_results]
        if not values:
            row[f"{metric}_mean"] = NA_VALUE
            row[f"{metric}_stddev"] = NA_VALUE
            row[f"{metric}_min"] = NA_VALUE
            row[f"{metric}_median"] = NA_VALUE
            row[f"{metric}_max"] = NA_VALUE
            continue
        row[f"{metric}_mean"] = statistics.mean(values)
        row[f"{metric}_stddev"] = statistics.stdev(values) if len(values) >= 2 else NA_VALUE
        row[f"{metric}_min"] = min(values)
        row[f"{metric}_median"] = statistics.median(values)
        row[f"{metric}_max"] = max(values)

    row["command"] = _get_stats_value(results, "command")

    assert tuple(row.keys()) == STATS_COLUMNS
    return row


def render_stats_tsv(timing, runs_requested):
    row = build_stats_row(timing=timing, runs_requested=runs_requested)
    header = "\t".join(STATS_COLUMNS)
    values = "\t".join(str(row[column]) for column in STATS_COLUMNS)
    return header + "\n" + values


def normalize_max_ram_kb(raw_value, raw_unit):
    raw_value = int(raw_value)
    if raw_unit == "bytes":
        return int(round(raw_value / 1000.0))
    if raw_unit == "kib":
        return int(round(raw_value * 1024.0 / 1000.0))
    raise ValueError(f"Unsupported memory unit: {raw_unit}")


class GnuTime(AbstractTime):

    def __init__(
        self,
        command,
        shell,
        time="/usr/bin/env time",
        experiment=None,
        max_ram_raw_unit="kib",
        debug=False,
    ):
        super().__init__(
            command=command,
            time=time,
            shell=shell,
            experiment=experiment,
            debug=debug,
        )

        self.gtime_columns_spec = "%e\t%U\t%S\t%P\t%M\t%x\t%I\t%O"
        self.gtime_columns = (
            "real_s", "user_s", "sys_s", "percent_cpu", "max_ram_kb", "exit_code", "fs_inputs",
            "fs_outputs"
        )
        self.max_ram_raw_unit = max_ram_raw_unit
        self.wrapper = lambda: f'{self.time_command} -o {self.current_tmp_fn()} -f "{self.gtime_columns_spec}"'

    def _parse_result(self):
        tmp_fn = self.current_tmp_fn()
        self._dlog(f"reading GNU time output from: {tmp_fn!r}")
        with open(tmp_fn) as tmp_fo:
            gtime_output_lines = [x.strip() for x in tmp_fo if x.strip()]
        self._dlog(f"raw non-empty lines: {gtime_output_lines!r}")
        gtime_output_values = None
        for line in reversed(gtime_output_lines):
            values = line.split("\t")
            if len(values) == len(self.gtime_columns):
                gtime_output_values = values
                break
        if gtime_output_values is None:
            raise RuntimeError(f"Unexpected GNU time output shape: {gtime_output_lines!r}")
        self._dlog(f"parsed values selected: {gtime_output_values!r}")
        # GNU time's %x is useful for metrics/debugging, but the shell wait status is the canonical exit code.
        for k, v in zip(self.gtime_columns, gtime_output_values):
            if k in {"percent_cpu", "exit_code"}:
                continue
            self.current_result.set(k, v)
        normalized_max_ram_kb = normalize_max_ram_kb(
            raw_value=self.current_result["max_ram_kb"], raw_unit=self.max_ram_raw_unit
        )
        self._dlog(f"normalized max RAM value: {normalized_max_ram_kb}")
        self.current_result.set(
            "max_ram_kb",
            normalized_max_ram_kb,
        )


class MacTime(AbstractTime):

    def __init__(self, command, shell, experiment=None, debug=False):
        super().__init__(
            command=command,
            time="/usr/bin/env time",
            shell=shell,
            experiment=experiment,
            debug=debug,
        )
        if sys.platform == "darwin":
            time_command = "/usr/bin/env time"
        else:
            raise Exception(f"Unsupported OS ({sys.platform})")

        self.wrapper = lambda: f'{self.time_command} -o {self.current_tmp_fn()} -l -p'

    def _read_mactime_dict(self):
        d = collections.OrderedDict()
        tmp_fn = self.current_tmp_fn()
        self._dlog(f"reading macOS time output from: {tmp_fn!r}")
        with open(tmp_fn) as tmp_fo:
            for x in tmp_fo:
                x = x.strip()
                v, k = x.split(maxsplit=1)
                if v in ["real", "user", "sys"]:
                    kk = v
                    vv = k
                else:
                    kk = k
                    vv = v
                if vv.isdigit():
                    vvv = int(vv)
                else:
                    vvv = vv
                d[kk] = vvv
        self._dlog(f"parsed dictionary: {d!r}")
        return d

    def _parse_result(self):
        d = self._read_mactime_dict()
        self.current_result.set("real_s", d["real"])
        self.current_result.set("user_s", d["user"])
        self.current_result.set("sys_s", d["sys"])
        normalized_max_ram_kb = normalize_max_ram_kb(
            raw_value=d["maximum resident set size"], raw_unit="bytes"
        )
        self._dlog(f"normalized max RAM value: {normalized_max_ram_kb}")
        self.current_result.set(
            "max_ram_kb",
            normalized_max_ram_kb,
        )

        #for k, v in zip(self.gtime_columns, gtime_output_values):
        #    self.current_result[k] = v


def run_timing(
    log_file,
    command,
    shell,
    experiment,
    gtime,
    repetitions,
    debug=False,
    stats_file=None,
):
    """
    Run a benchmarking command and log the results.

    Args:
        log_file (str): The path to the log file where the results will be logged.
        experiment (str): Optional experiment name to include in the log.
        command (str): The benchmarking command to run.
        shell (str): Shell for execution.
        gtime (bool): Whether to use gtime as a command.

    Returns:
        None
    """

    platf = sys.platform
    log_debug(debug, f"starting {PROGRAM} {__version__}")
    log_debug(debug, f"parsed command: {command!r}")
    log_debug(debug, f"shell: {shell!r}")
    log_debug(debug, f"repetitions: {repetitions}")
    log_debug(debug, f"log destination: {log_file!r}")
    log_debug(debug, f"stats destination: {stats_file!r}")
    log_debug(debug, f"experiment name: {experiment!r}")
    log_debug(debug, f"platform: {platf}")
    # if gtime, run gtime everywhere & always GNU output; platform-specific behaviour
    if gtime:
        log_debug(debug, "backend: GNU time via /usr/bin/env gtime")
        t = GnuTime(
            command=command,
            experiment=experiment,
            time="/usr/bin/env gtime",
            shell=shell,
            debug=debug,
        )
    else:
        if platf == "linux":
            log_debug(debug, "backend: GNU time via /usr/bin/env time on Linux")
            t = GnuTime(
                command=command,
                experiment=experiment,
                shell=shell,
                debug=debug,
            )
        elif platf == "darwin":
            log_debug(debug, "backend: macOS /usr/bin/env time -l -p on Darwin")
            t = MacTime(
                command=command,
                experiment=experiment,
                shell=shell,
                debug=debug,
            )
        else:
            raise Exception(f"Unsupported OS ({platf})")

    t.run(times=repetitions)

    if stats_file is not None:
        Path(stats_file).parent.mkdir(parents=True, exist_ok=True)
        with open(stats_file, "w") as fo:
            print(render_stats_tsv(timing=t, runs_requested=repetitions), file=fo)

    log_debug(debug, f"output destination: {log_file!r}")
    if log_file == "stdout" or log_file == "-":
        print(t)
    elif log_file == "stderr":
        print(t, file=sys.stderr)
    else:
        Path(log_file).parent.mkdir(parents=True, exist_ok=True)
        with open(log_file, "w") as fo:
            print(t, file=fo)

    final_exit_code = t.get_final_exit_code()
    log_debug(debug, f"final exit code: {final_exit_code}")
    return final_exit_code


def main():
    """
    The main function of the script. It parses the command line arguments, runs the benchmarking command,
    and logs the results.
    """

    class CustomArgumentParser(argparse.ArgumentParser):

        def __init__(self, prog=None, **kwargs):
            super().__init__(prog="galitime", **kwargs)

        def print_help(self):
            """
            Prints the help message.

            Returns:
                None
            """
            msg = self.format_help()
            repl = re.compile(r'\]\s+\[')
            msg = repl.sub("] [", msg)
            msg = re.sub(r"\s+\[-h\]", "", msg)
            msg = re.sub(r"\s+\[-v\]", "", msg)
            msg = msg.replace(", --help", "        ")
            print(msg)

        def format_help(self):
            formatter = self._get_formatter()
            formatter.add_text(" \n" + self.description)
            formatter.add_usage(self.usage, self._actions, self._mutually_exclusive_groups)
            formatter.add_text(self.epilog)

            # positionals, optionals and user-defined groups
            for action_group in self._action_groups:
                formatter.start_section(action_group.title)
                formatter.add_text(action_group.description)
                formatter.add_arguments(action_group._group_actions)
                formatter.end_section()

            return formatter.format_help()

    parser = CustomArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description="Program: {} ({})\n".format(PROGRAM, DESC) +
        "Version: {}\n".format(__version__) + "Contact: Karel Brinda <karel.brinda@inria.fr>",
        usage="galitime [-d] [-r INT] [-g] [-l FILE] [-S FILE] [-n STR] [-s STR] [--] command [arg ...]",
        epilog=(
            "\n"
            "command modes:\n"
            "  argv-like mode:      galitime sleep 0.1\n"
            "  shell-command mode:  galitime \"echo a && echo b\"\n"
            "\n"
            "notes:\n"
            "  - use quotes when your command includes shell syntax such as: redirection ('>'),\n"
            "    pipelines ('|'), '&&', ';', globbing, or command substitution\n"
            "  - use -- to explicitely mark the start of the benchmarked command when needed\n"
            "  - argv-like mode is only guaranteed for POSIX-like shells"
        ),
    )

    parser.add_argument(
        'command',
        nargs='*',
        help='the command to be benchmarked',
    )

    parser.add_argument(
        '-v',
        action='version',
        version='{} {}'.format(PROGRAM, __version__),
    )

    parser.add_argument(
        '-d', '--debug', dest='debug', action='store_true',
        help='print detailed debug trace to stderr'
    )

    parser.add_argument(
        '-r', '--reps', dest='reps', metavar='INT', type=int, default=DEFAULT_r,
        help=f'number of repetitions [{DEFAULT_r}]'
    )

    parser.add_argument(
        '-g', '--gtime', dest='gtime', action='store_true',
        help=f'call gtime instead of time (useful on MacOS)'
    )

    parser.add_argument(
        '-l', '--log', dest='log', metavar='FILE', default=DEFAULT_l,
        help=f'output (filename/stderr/stdout) [{DEFAULT_l}]'
    )

    parser.add_argument(
        '-S', '--stats', dest='stats', metavar='FILE', default=None,
        help='write summary statistics TSV to FILE [disabled]'
    )

    parser.add_argument(
        '-n', '--name', metavar='STR', help='name of the experiment (for output)',
        dest='experiment', default=None
    )

    parser.add_argument(
        '-s', '--shell', metavar='STR', help=f'shell for execution [{DEFAULT_s}]',
        default=DEFAULT_s, dest='shell'
    )

    option_argv, command_argv, fallback_to_argparse = split_cli_argv(parser, sys.argv[1:])
    if fallback_to_argparse:
        args = parser.parse_args(sys.argv[1:])
        command_argv = args.command
    else:
        args = parser.parse_args(option_argv)
    if args.stats in {"stdout", "stderr", "-"}:
        parser.error("--stats requires a real file path")
    if not command_argv:
        parser.error("the following arguments are required: command")
    # The logged "command" field intentionally matches the exact string we execute:
    # a single token is preserved verbatim, otherwise the argv tail is rebuilt with shlex.join.
    if len(command_argv) == 1:
        command = command_argv[0]
    else:
        command = shlex.join(command_argv)

    r = run_timing(
        log_file=args.log,
        stats_file=args.stats,
        experiment=args.experiment,
        command=command,
        gtime=args.gtime,
        shell=args.shell,
        repetitions=args.reps,
        debug=args.debug,
    )

    return r


if __name__ == "__main__":
    r = main()
    sys.exit(r)
